version: "3"

networks:
  rss-service:
    driver: bridge
services:
  api:
    container_name: go-api
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    networks:
      - rss-service
  
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - rss-service
    depends_on:
      - api
