version: "3"

networks:
  rss-service:
    driver: bridge
services:
  api:
    container_name: go-api
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    networks:
      - rss-service

  frontend:
    container_name: frontend
    image: node:current
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: /bin/bash -c 'npm run start'
    networks:
      - rss-service
    depends_on:
      - api
